---
# Playbook to configure provisioned openstack instances
- import_playbook: in-memory-inventory.yml

- name: "Configure OpenStack instances using In-Memory Inventory"
  hosts: app_servers:database_servers:load_balancers
  become: yes
  gather_facts: false
  vars_files:
    - vars/common.yml
  pre_tasks:
    - name: "Wait 5min for OpenStack deployment instances to be ready for connections"
      wait_for_connection:
  tasks:
    - name: "Configure DNS and Satellite"
      include_role:
        name: configure_satellite
