---
# Only use in-memory inventory when not running in Tower
- import_playbook: in-memory-inventory.yml
  when: awx_job_id is not defined

- name: "Deploy, configure, and populate flask repo and virtualenv"
  hosts: app_servers
  become: true
  gather_facts: false
  tags:
    - application_servers
    - flask
  roles:
    - flask
