---
# Playbook to configure provisioned openstack instances
- name: "Configure OpenStack instances using In-Memory Inventory"
  hosts: app_servers:database_servers:load_balancers
  become: yes
  gather_facts: false
  vars_files:
    - vars/common.yml
  tasks:
    - name: "Configure DNS and Satellite"
      include_role:
        name: configure_satellite
