---
- name: "In-Memory Inventory"
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - vars/common.yml
  tasks:
    - name: "Collect OpenStack instance info"
      os_server_info:
        cloud: "{{ guid }}-project"
      register: instances

    - name: "Build In-Memory inventory"
      add_host:
        host: "{{ __instance.name }}.{{ internal_domain }}"
        group: "{{ __instance.metadata.AnsibleGroup }}"
        ansible_host: "{{ __instance.private_v4 }}"
        ssh_private_key_file: "{{ home }}/.ssh/{{ guid }}key.pem"
      when: __instance.metadata.deployment_name is defined and __instance.metadata.deployment_name == "{{ deployment_name }}"
      loop: "{{ instances.openstack_servers }}"
      loop_control:
        loop_var: __instance

- name: "Print current hosts"
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - debug:
        var: groups

- name: "Verify OpenStack deployment instances"
  hosts: all
  tasks:
    - name: "Wait 5min for OpenStack deployment instances to be ready for connections"
      wait_for_connection:

    - name: "Verify connectivity"
      ping:
      register: output

    - debug:
        msg: "{{ output }}"
