---
# Provision OpenStack instances and configure them
- name: "Create and configure infrastructure"
  vars:
    instance_state: present

- import_playbook: provision-instances.yml

- import_playbook: in-memory-inventory.yml

- import_playbook: configure-instances.yml
