---
# Provision OpenStack instances and configure them
- name: "Create and configure infrastructure"
  vars:
    instance_state: present

- import_playbook: provision-instances.yml

# Only use in-memory inventory when not running in Tower
- import_playbook: in-memory-inventory.yml
  when: awx_job_id is not defined

- import_playbook: configure-instances.yml
