---
# Only use in-memory inventory when not running in Tower
- import_playbook: in-memory-inventory.yml
  when: awx_job_id is not defined

- name: "Deploy HAProxy load balancer"
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers
  roles:
    - haproxy
