---
- import_playbook: in-memory-inventory.yml

- name: "Deploy HAProxy load balancer"
  hosts: load_balancers
  gather_facts: false
  become: true
  tags:
    - load_balancers
  roles:
    - haproxy
    - role: firewall
      vars:
        firewall_services:
          - http
